// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://catqclhhgzvojheivfvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdHFjbGhoZ3p2b2poZWl2ZnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI5MDgsImV4cCI6MjA2NTQ5ODkwOH0.8kTlbeKBh-kQnaBC_xcd_5IUpXKHApqvPSSNs0Et8wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);